version: '3.8'

services:
  express:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - database_data:/data
      - ./website:/app
    environment:
      REDIS_HOST: redis
      SQLITE_DB_PATH: ${DB_PATH}
      NODE_ENV: development
    command: ["npm", "start", "dev"]

  # redis:
  #   image: "redis:7.0"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  redis_data:
  database_data:
