name: ExpressJS Test

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start application
      run: docker compose up --build -d
    
    - name: Wait for application to be ready
      run: |
        for i in `seq 1 30`; do
          nc -z localhost 3000 && echo "Express.js is up!" && exit 0
          echo "Waiting for Express.js to be up..."
          sleep 1
        done
        echo "Express.js did not start in time" && exit 1
